import React from "react";
import {
  SiAngular,
  SiFlutter,
  SiReact,
  SiFirebase,
  SiDjango,
  SiNodedotjs,
  SiGithub,
  SiTailwindcss,
  SiHtml5,
  SiAdobexd,
  SiFigma,
  SiLinux,
  SiApple,
  SiAndroid,
  SiAdobeillustrator,
  SiAdobephotoshop,
  SiClickup,
  SiSwift,
  SiLaravel,
  SiMedium,
  SiDevdotto,
  SiTauri,
  SiCss3,
} from "react-icons/si";
import { FaChrome, FaProjectDiagram, FaTasks, FaTools } from "react-icons/fa";
import {
  FaMobileAlt,
  FaDesktop,
  FaGlobe,
  FaServer,
  FaPencilRuler,
  FaWindows,
} from "react-icons/fa";
import { IoLogoGooglePlaystore } from "react-icons/io5";

export const tags = {
  flutter: {
    name: "Flutter",
    textColor: "#49b5ea",
    icon: <SiFlutter color="#49b5ea" />,
    website: "https://flutter.dev/",
  },
  react: {
    name: "React",
    textColor: "#61DAFB",
    icon: <SiReact color="#61DAFB" />,
    website: "https://reactjs.org/",
  },
  angular: {
    name: "Angular",
    textColor: "#DD0031",
    icon: <SiAngular color="#DD0031" />,
    website: "https://angular.io/",
  },
  firebase: {
    name: "Firebase",
    textColor: "#FFA611",
    icon: <SiFirebase color="#FFA611" />,
    website: "https://firebase.google.com/",
  },
  django: {
    name: "Django",
    textColor: "#092D1F",
    icon: <SiDjango color="#092D1F" />,
    website: "https://www.djangoproject.com/",
  },
  nodejs: {
    name: "NodeJS",
    textColor: "#339933",
    icon: <SiNodedotjs color="#339933" />,
    website: "https://nodejs.org/",
  },
  github: {
    name: "Github",
    textColor: "#181707",
    icon: <SiGithub color="#181707" />,
    website: "https://github.com/",
  },
  tailwind: {
    name: "Tailwind",
    textColor: "#38B2AC",
    icon: <SiTailwindcss color="#38B2AC" />,
    website: "https://tailwindcss.com/",
  },
  html: {
    name: "HTML5",
    textColor: "#E34F26",
    icon: <SiHtml5 color="#E34F26" />,
    website: "https://html.spec.whatwg.org/multipage/",
  },
  adobeXD: {
    name: "Adobe XD",
    textColor: "#FF2BC2",
    icon: <SiAdobexd color="#FF2BC2" />,
    website: "https://www.adobe.com/products/xd.html",
  },
  figma: {
    name: "Figma",
    textColor: "#F24E1E",
    icon: <SiFigma color="#F24E1E" />,
    website: "https://www.figma.com/",
  },
  web: {
    name: "Web",
    textColor: "#61DAFB",
    icon: <FaChrome color="#61DAFB" />,
    website: "https://www.w3.org/",
  },
  linux: {
    name: "Linux",
    textColor: "#FCC624",
    icon: <SiLinux color="#FCC624" />,
    website: "https://www.linux.org/",
  },
  macos: {
    name: "macOS",
    textColor: "#000000",
    icon: <SiApple color="#000000" />,
    website: "https://www.apple.com/macos",
  },
  windows: {
    name: "Windows",
    textColor: "#0078D6",
    icon: <FaWindows color="#0078D6" />,
    website: "https://www.microsoft.com/windows/",
  },
  android: {
    name: "Android",
    textColor: "#3DDC84",
    icon: <SiAndroid color="#3DDC84" />,
    website: "https://www.android.com/",
  },
  ios: {
    name: "iOS",
    textColor: "#000000",
    icon: <SiApple color="#000000" />,
    website: "https://www.apple.com/ios/ios-15/",
  },
  adobeIllustrator: {
    name: "Adobe Illustrator",
    textColor: "#FF9A00",
    icon: <SiAdobeillustrator color="#FF9A00" />,
    website: "https://www.adobe.com/products/illustrator",
  },
  adobePhotoshop: {
    name: "Adobe Photoshop",
    textColor: "#31A8FF",
    icon: <SiAdobephotoshop color="#31A8FF" />,
    website: "https://www.adobe.com/products/photoshop.html",
  },
  oneCodeBase: {
    name: "One Codebase",
    textColor: "#32CD32",
    icon: <SiFlutter color="#32CD32" />,
    website: "https://flutter.dev/multi-platform",
  },
  uiuxDesign: {
    name: "UI/UX Design",
    textColor: "#EB3C29",
    icon: <FaPencilRuler color="#EB3C29" />,
    website: undefined,
  },
  mobileDev: {
    name: "Mobile",
    textColor: "#4CAF50",
    icon: <FaMobileAlt color="#4CAF50" />,
    website: undefined,
  },
  desktopDev: {
    name: "Desktop",
    textColor: "#0078D6",
    icon: <FaDesktop color="#0078D6" />,
    website: undefined,
  },
  webDev: {
    name: "Web",
    textColor: "#61DAFB",
    icon: <FaGlobe color="#61DAFB" />,
    website: undefined,
  },
  backendDev: {
    name: "Backend",
    textColor: "#FCC624",
    icon: <FaServer color="#FCC624" />,
    website: undefined,
  },
  clickup: {
    name: "ClickUp",
    textColor: "#7B68EE",
    icon: <SiClickup color="#7B68EE" />,
    website: "https://clickup.com/",
  },
  swift: {
    name: "Swift",
    textColor: "#FA7343",
    icon: <SiSwift color="#FA7343" />,
    website: "https://swift.org/",
  },
  rocketTimer: {
    name: "Rocket Timer",
    textColor: "#49b5ea",
    icon: <SiFlutter color="#49b5ea" />,
    website: "https://pub.dev/packages/rocket_timer",
  },
  flutterRocket: {
    name: "Flutter Rocket",
    textColor: "#49b5ea",
    icon: <SiFlutter color="#49b5ea" />,
    website: "https://pub.dev/packages/flutter_rocket",
  },
  hafs: {
    name: "Hafs | حفص",
    textColor: "#019875",
    icon: <IoLogoGooglePlaystore color="#019875" />,
    website: "https://play.google.com/store",
  },
  warsh: {
    name: "Warsh | ورش",
    textColor: "#30AADD",
    icon: <IoLogoGooglePlaystore color="#30AADD" />,
    website: "https://play.google.com/store",
  },
  CiCd: {
    name: "CI-CD",
    textColor: "#5D5FEF",
    icon: <FaProjectDiagram color="#5D5FEF" />,
    website: "https://resources.github.com/ci-cd/",
  },
  projectManagement: {
    name: "Project Management",
    textColor: "#ffd700",
    icon: <FaTasks color="#ffd700" />,
    website: undefined,
  },
  laravel: {
    name: "Laravel",
    textColor: "#FF2D20",
    icon: <SiLaravel color="#FF2D20" />,
    website: "https://laravel.com/",
  },
  medium: {
    name: "Medium",
    textColor: "#00ab6c",
    icon: <SiMedium color="#00ab6c" />,
    website: "https://medium.com/",
  },
  devto: {
    name: "DEV.to",
    textColor: "#0a0a0a",
    icon: <SiDevdotto color="#0a0a0a" />,
    website: "https://dev.to/",
  },
  underDevelopment: {
    name: "Under Development",
    textColor: "#FFA500",
    icon: <FaTools color="#FFA500" />,
    website: undefined,
  },
  googleGemini: {
    name: "Google Gemini",
    textColor: "#4285F4",
    icon: <SiFirebase color="#4285F4" />,
    website: "https://gemini.google.com/",
  },
  fastapi: {
    name: "FastAPI",
    textColor: "#009688",
    icon: <SiReact color="#009688" />,
    website: "https://fastapi.tiangolo.com/",
  },
  tauri: {
    name: "Tauri",
    textColor: "#FFC131",
    icon: <SiTauri color="#FFC131" />,
    website: "https://v2.tauri.app/",
  },
  css: {
    name: "CSS",
    textColor: "#1572B6",
    icon: <SiCss3 color="#1572B6" />,
    website: "https://www.w3.org/Style/CSS/",
  },
};
